language: php

php:
    - 5.3
    - 5.4
    - 5.5
    
matrix:
    allow_failures:
    - php: 5.5    

env:
    - SYMFONY_VERSION=2.0.*
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=dev-master

before_script:
    - composer install --dev
    
script: 
    - bin/phpunit -c app/ --coverage-clover clover.xml
    
after_vendor:
    - bin/coveralls 

notifications:
    email:
        - raffaellobertini@gmail.com
