services:
    sonata.admin.post:
        class: Acme\UserBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Acme\BlogBundle\Entity\Post
            - SonataAdminBundle:CRUD
            - ~
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]
            #- [ setTranslationDomain, [AcmeBlogBundle, AcmeUserBundle]]
    
    sonata.admin.user:
        class: Acme\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "Username" }
        arguments:
            - ~
            - Acme\UserBundle\Entity\User
            - SonataAdminBundle:CRUD
            - ~
        calls:
            - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]