#services:
    #sonata.admin.user:
    #    class: Acme\UserBundle\Admin\UserAdmin
    #    tags:
    #        - { name: sonata.admin, manager_type: orm, group: "User", label: "Username" }
    #    arguments:
    #        - ~
    #        - Acme\UserBundle\Entity\User
            #- Application\Sonata\UserBundle\Entity\User
            #- SonataAdminBundle:CRUD
    #        - ~
    #    calls:
    #        - [ setLabelTranslatorStrategy, ["@sonata.admin.label.strategy.underscore"]]